bot.py, findMatches.py
like we discussed, i removed the getCopa command and turned getEuro into getInternationalCup(leagueCode = 50, endDate = 20210711) which sets the euros parameters as default since that's what they were originally created for.  
my testing works, but don't have a way to create my own wenger bot so need you to test now.
Thanks,
Ren
=> removed getCopa() function and refactored getEuro into getInternationalCup()

bot.py
User can send a !olympics message and wengy replies back with both the mens and womens tournaments.
=> Added olympics tournaments 

bot.py, findMatches.py
Hey Andy,
I've fixed the bugs in my original pull request and i've added a "next" command.  Please test at your earliest convenience.
Thanks,
Ren
=> added "fixtures #" command and "next" command

findMatches.py
Hey Andy,
user noticed that !next command was one hour off and explained it was because I didn't think about BST.  I have since fixed that issue.  Please review and test at your earliest convenience.
Thanks,
Ren
=> Fixed the nextFixture command to account for British Summer Time.

bot.py
=> Send the results fetched to Discord

findMatches.py
Command now shows, for example, 'Next match is Burnley (H) in 17 hours, 26 minutes'. Addresses #38.
=> Added team to play to !next command

bot.py, playerstats.py
Resolves #41 
` python .\bot.py `
Output: Posted in #rubber-ducky
=> Add playerstats helper function and implement !goals command

playerstats.py
=> Pretty output !goals command

cogs/facts.py, cogs/fixtures.py
=> Make the !fixtures, !next and manager !fact commands look a bit nicer using embeds

cogs/playerstats.py
also turned it into an embed, and provided more teams and links to their icons.
=> fixed !goals so that it properly sorts players and shows players who have scored >=10

cogs/transfers.py
The command works
```
Eabryt — Today at 12:55
!anysignings
Arsene Wenger
BOT — Today at 12:55
Fuck All```
=> Adding anysignings command for #69

cogs/transfers.py
Was needlessly incrementing the year,
=> Fixing some code now that we have actual transfers. 

cogs/playerstats.py, cogs/tables.py
Please review and approve this PR.  I have made the changes requested by Flix in the last PR.
=> added !injuires command and completed PL table for !goals command

cogs/fixtures.py
We weren't sending a User Agent, so we were getting blocked by Arsenal.
Fixes https://github.com/AndyReifman/ArseneWenger/issues/95
=> Fix Fixtures/Results/Next cogs.

cogs/playerstats.py, utils.py
This relies on a season being between August and May.
=> Make the assists command date dynamic

cogs/twitter_link_fixer.py
=> Add new cog to fix every Twitter link

cogs/playerstats.py
also greatly simplified its logic.
=> Fix injuries command

cogs/fixtures.py
and added some try-catches so wenger isn't stuck in a 'thinking' state
=> fixed some more parsing issues 

cogs/reactions.py
Salty Tottenham fans have made a request.
=> Restricting message reactions for Tottenham to gunners only.

cogs/reactions.py
Also @AndyReifman , you need to update pandas so that playerstats.py can load again.
=> added reactions to city, man city, and manchester city
